USE PLGALGA;

CREATE TABLE PLGALGA.TB_CATEGORIA_LANCAMENTO(
	CODIGO				BIGINT(20)				PRIMARY KEY			AUTO_INCREMENT,
	NOME				VARCHAR(50)				NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('ALIMENTAÇÃO');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('AÇOUGUE');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('LAZER');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('LAZER');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('CONSULTA MÉDICA');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('MEDICAMENTOS');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('EXAMES MÉDICOS');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('INTERNET FIXA');
INSERT INTO PLGALGA.TB_CATEGORIA_LANCAMENTO(NOME) VALUES ('TELEFÔNIA MÓVEL');